DROP TABLE IF EXISTS ABILITIES;
CREATE TABLE ABILITIES
(
  ABILITY_ID SERIAL,
  NAME VARCHAR(64) NOT NULL,
  SHORT_NM VARCHAR(3) NOT NULL,
  DESCRIPTION VARCHAR(255),
  VALUE INT NOT NULL,
  MODIFIER INT NOT NULL,
  PRIMARY KEY (ABILITY_ID)
);

/*
INSERT THIS FOR A TEST ABILITY
*/

INSERT INTO ABILITIES
VALUES (1, 'STRENGTH', 'STR', 'Strength of the character', 0, 0);

INSERT INTO ABILITIES
VALUES (2, 'STAMINA', 'STA', 'Stamina of the character', 0, 0);


/* LAST TWO VALUES MUST ALWAYS BE 0. THEY ARE SET IN THE CHAR BUILDER ! */