DROP TABLE IF EXISTS ABILITIES;
CREATE TABLE ABILITIES
(
  ABILITY_ID INT NOT NULL UNIQUE AUTO_INCREMENT,
  NAME VARCHAR(64) NOT NULL,
  SHORT_NM VARCHAR(3) NOT NULL,
  DESCRIPTION VARCHAR(255),
  PRIMARY KEY (ABILITY_ID)
);

/*
INSERT THIS FOR A TEST ABILITY
*/

INSERT INTO ABILITIES
VALUES (1, 'STRENGTH', 'STR', 'Strength of the character');