DROP TABLE IF EXISTS ASSETS;
CREATE TABLE ASSETS
(
  ASSET_ID SERIAL,
  URL VARCHAR(255) NOT NULL,
  CATEGORY VARCHAR(64),
  ORIENTATION VARCHAR(64),
  PRIMARY KEY (ASSET_ID)
);


INSERT INTO ASSETS
VALUES (1, 'this is an url', 'CATEGORYTEST', 'ORIENTATIONTEST');
