DROP TABLE IF EXISTS CAMPAIGNS;
CREATE TABLE CAMPAIGNS
(
  CAMPAIGN_ID SERIAL,
  NAME VARCHAR(64) NOT NULL,
  GM_ID INT NOT NULL,
  PRIMARY KEY (CAMPAIGN_ID)
);


INSERT INTO CAMPAIGNS
VALUES (2, 'L\'éveil du seigneur des runes', 1);
