DROP TABLE IF EXISTS CHAR_CLASS;
CREATE TABLE CHAR_CLASS
(
  CHAR_CLASS_ID INT NOT NULL UNIQUE AUTO_INCREMENT,
  CHAR_ID INT NOT NULL,
  CLASS_ID INT NOT NULL,
  CLASS_LEVEL INT NOT NULL,
  PRIMARY KEY (CHAR_CLASS_ID)
);

/*
INSERT THIS FOR A TEST CHAR_CLASS
*/

INSERT INTO CHAR_CLASS
VALUES (1, 1, 1, 1);
/*wizard*/
