DROP TABLE IF EXISTS CLASS_FEATS;
CREATE TABLE CLASS_FEATS
(
  CLASS_FEAT_ID INT NOT NULL UNIQUE AUTO_INCREMENT,
  CLASS_ID INT NOT NULL,
  NAME VARCHAR (255),
  TYPE INT NOT NULL,
  PRIMARY KEY (CLASS_FEAT_ID)
);

/*
INSERT THIS FOR A TEST CLASS FEAT
*/

INSERT INTO CLASS_FEATS
VALUES (1, 1, 'Stunning Fist', 1);
