DROP TABLE IF EXISTS CLASS_FEATS;
CREATE TABLE CLASS_FEATS
(
  CLASS_FEAT_ID SERIAL,
  CLASS_ID INT NOT NULL,
  FEAT_ID INT NOT NULL,
  PRIMARY KEY (CLASS_FEAT_ID)
);

/*
INSERT THIS FOR A TEST CLASS FEAT
*/

INSERT INTO CLASS_FEATS
VALUES (1, 1, 1);
/*stunning fist*/