DROP TABLE IF EXISTS CURRENCIES;
CREATE TABLE CURRENCIES
(
  CURRENCY_ID INT NOT NULL UNIQUE AUTO_INCREMENT,
  NAME VARCHAR(64) NOT NULL,
  SHORT_NM VARCHAR(3) NOT NULL,
  DESCRIPTION VARCHAR(255),
  PRIMARY KEY (CURRENCY_ID)
);

/*
INSERT THIS FOR A TEST CURRENCY
*/

INSERT INTO CURRENCIES
VALUES (1, 'Gold', 'G', 'Gold pieces');