DROP TABLE IF EXISTS GEAR;
CREATE TABLE GEAR
(
  GEAR_ID INT NOT NULL UNIQUE AUTO_INCREMENT,
  NAME VARCHAR(64) NOT NULL,
  TYPE_ID INT, /*TABLE GEAR_TYPE*/
  MODIFIER INT,
  ABILITY_ID INT,
  DESCRIPTION VARCHAR(255),
  PRIMARY KEY (GEAR_ID)
);

/*
INSERT THIS FOR A TEST GEAR
*/

INSERT INTO GEAR
VALUES (1, 'THE ULTIMATE BEATDOWN', 1, 1000000, 1, 'Kills anything in 1 hit.');