DROP TABLE IF EXISTS GEAR_TYPE;
CREATE TABLE GEAR_TYPE
(
  GEAR_TYPE_ID SERIAL,
  NAME VARCHAR(64) NOT NULL,
  DESCRIPTION VARCHAR(255),
  PRIMARY KEY (GEAR_TYPE_ID)
);

/*
INSERT THIS FOR A TEST GEAR TYPE
*/

INSERT INTO GEAR_TYPE
VALUES (1, 'EQUIPMENT', 'Can be equipped as weapon/armor');