DROP TABLE IF EXISTS GEAR;
CREATE TABLE GEAR
(
  GEAR_ID INT NOT NULL UNIQUE AUTO_INCREMENT,
  NAME VARCHAR(64) NOT NULL,
  TYPE_ID INT, /*TABLE GEAR_TYPE*/
  MODIFIER INT, /* EXAMPLE +2 TO...*/
  ABILITY_ID INT, /* TABLE ABILITIES */
  DESCRIPTION VARCHAR(1000),
  PRICE int,
  CURRENCY_ID int, /* TABLE CURRENCY */
  WEIGHT int,
  WEIGHT_UNIT VARCHAR(4),
  DMG_SMALL VARCHAR(16),
  DMG_MIDDLE VARCHAR(16),
  CRITICAL VARCHAR(16),
  ITEM_RANGE VARCHAR(16),
  SPECIAL VARCHAR(255),
  PRIMARY KEY (GEAR_ID)
);

/*
INSERT THIS FOR A TEST GEAR
*/

INSERT INTO GEAR
VALUES (1, 'THE ULTIMATE BEATDOWN', 1, 1000000, 1, 'Kills anything in 1 hit.', 999999, 1, 1, 'kg', '1000d20', '1000d20', 'x9999', null, null);

INSERT INTO GEAR
VALUES (2, 'The underwear of strength', 1, 1000000, 1, 'An underwear that makes you strong', null, 1, 1, 'kg', null, null, null, null, null);