DROP TABLE IF EXISTS MODIFIER_TABLE;
CREATE TABLE MODIFIER_TABLE
(
  MODIFIER_TABLE_ID SERIAL,
  MATRIX_VALUE INT NOT NULL,
  PRIMARY KEY (MODIFIER_TABLE_ID)
);

/*
This is a matrix for computing modifier. It's not meant to be changed ! EVER.
*/
