DROP TABLE IF EXISTS PLAYERS;
  CREATE TABLE PLAYERS
   (
	PLAYER_ID SERIAL,
	NAME VARCHAR(32) NOT NULL,
	PASSWORD VARCHAR(32) NOT NULL, 
	EMAIL VARCHAR(64) UNIQUE NOT NULL,
	CREDENTIALS INT NOT NULL,
    CREATION_DATE TIMESTAMP,
    PRIMARY KEY (PLAYER_ID)
    );

/*
INSERT THIS FOR TEST PLAYER
*/

INSERT INTO PLAYERS
VALUES (
           1,
           'Jerome',
           '1234',
           'mymail',
           1,
           CURRENT_TIMESTAMP
           );