DROP TABLE IF EXISTS RACES;
  CREATE TABLE RACES
   (
	RACE_ID SERIAL,
	NAME VARCHAR(32) UNIQUE NOT NULL,
	SIZE VARCHAR(3) NOT NULL,
  PRIMARY KEY (RACE_ID)
    );

/*
INSERT THIS FOR TEST RACE
 */

INSERT INTO races
VALUES (
           1,
           'Humain',
           'M'
           );