DROP TABLE IF EXISTS SKILLS;
CREATE TABLE SKILLS
(
  SKILL_ID INT NOT NULL UNIQUE AUTO_INCREMENT,
  NAME VARCHAR(64) NOT NULL,
  PRIMARY_STAT VARCHAR(3) NOT NULL,
  DESCRIPTION VARCHAR(255),
  PRIMARY KEY (SKILL_ID)
);

/*
INSERT THIS FOR A TEST SKILL
*/

INSERT INTO SKILLS
VALUES (1, 'CLIMB', 'STR', 'Ability to climb walls/cliffs/other');
